name: Gamestore deploy

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Prepare plugins and theme zip
      run: zip -r wpcontent.zip plugins mu-plugins themes

    - name: Copy Zips to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "./wpcontent.zip"
        target: ${{ github.event_name == 'push' &&  '/www/bestweb.in.ua/wp-content/test' }}
        